version: '3.8'
services:
  app:
  build: .
  container_name: web-renderer-app
  env_file: .env
  ports:
    - "3000:3000"
  depends_on:
    - redis
  restart: unless-stopped

redis:
  image: redis:7
  container_name: web-renderer-redis
  volumes:
    - redis-data:/data
  restart: unless-stopped

nginx:
  image: nginx:stable-alpine
  container_name: web-renderer-nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginc/conf.d/default.conf:ro
  depends_on:
    - app
  restart: unless-stopped

volumes:
  redis-data: